name: igv_2526
services:
  dbgis_igv:
    image: postgis/postgis:latest
    container_name: postgis_igv
    restart: unless-stopped # always
    ports: 
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: geoportal_db
    volumes:
      - pg_data_igv:/var/lib/postgresql/data
      - type: bind
        source: ./sql_files
        target: /docker-entrypoint-initdb.d
    networks:
      - postgres_network
      
  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_igv
    restart: unless-stopped # always
    depends_on:
      - dbgis_igv
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False' # pgAdmin runs in a single-user desktop mode, which is more akin to a standalone application
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 50 # Only log critical errors
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - type: bind
        source: ./sql_files
        target: /home/sql_files
    networks:
      - postgres_network

  geoserver:
    image: docker.osgeo.org/geoserver:2.28.4
    container_name: geoserver_igv
    restart: unless-stopped
    depends_on:
      - dbgis_igv
    ports:
      - '8080:8080'
    environment:
      CORS_ENABLED: 'true'
      CORS_ALLOWED_ORIGINS: '*'
    volumes:
      - geoserver_data:/opt/geoserver_data
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge
    
volumes:
  pg_data_igv:
  pgadmin_data:
  geoserver_data:
